package io.akhilennu.chatbot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BotAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBotAllPropertiesEquals(Bot expected, Bot actual) {
        assertBotAutoGeneratedPropertiesEquals(expected, actual);
        assertBotAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBotAllUpdatablePropertiesEquals(Bot expected, Bot actual) {
        assertBotUpdatableFieldsEquals(expected, actual);
        assertBotUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBotAutoGeneratedPropertiesEquals(Bot expected, Bot actual) {
        assertThat(actual)
            .as("Verify Bot auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBotUpdatableFieldsEquals(Bot expected, Bot actual) {
        assertThat(actual)
            .as("Verify Bot relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBotUpdatableRelationshipsEquals(Bot expected, Bot actual) {
        // empty method
    }
}
