package io.akhilennu.chatbot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IntentResponseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentResponseAllPropertiesEquals(IntentResponse expected, IntentResponse actual) {
        assertIntentResponseAutoGeneratedPropertiesEquals(expected, actual);
        assertIntentResponseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentResponseAllUpdatablePropertiesEquals(IntentResponse expected, IntentResponse actual) {
        assertIntentResponseUpdatableFieldsEquals(expected, actual);
        assertIntentResponseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentResponseAutoGeneratedPropertiesEquals(IntentResponse expected, IntentResponse actual) {
        assertThat(actual)
            .as("Verify IntentResponse auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentResponseUpdatableFieldsEquals(IntentResponse expected, IntentResponse actual) {
        assertThat(actual)
            .as("Verify IntentResponse relevant properties")
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentResponseUpdatableRelationshipsEquals(IntentResponse expected, IntentResponse actual) {
        // empty method
    }
}
