package io.akhilennu.chatbot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IntentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentAllPropertiesEquals(Intent expected, Intent actual) {
        assertIntentAutoGeneratedPropertiesEquals(expected, actual);
        assertIntentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentAllUpdatablePropertiesEquals(Intent expected, Intent actual) {
        assertIntentUpdatableFieldsEquals(expected, actual);
        assertIntentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentAutoGeneratedPropertiesEquals(Intent expected, Intent actual) {
        assertThat(actual)
            .as("Verify Intent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentUpdatableFieldsEquals(Intent expected, Intent actual) {
        assertThat(actual)
            .as("Verify Intent relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentUpdatableRelationshipsEquals(Intent expected, Intent actual) {
        assertThat(actual)
            .as("Verify Intent relationships")
            .satisfies(a -> assertThat(a.getResponse()).as("check response").isEqualTo(expected.getResponse()))
            .satisfies(a -> assertThat(a.getBot()).as("check bot").isEqualTo(expected.getBot()))
            .satisfies(a -> assertThat(a.getEntities()).as("check entities").isEqualTo(expected.getEntities()));
    }
}
