package io.akhilennu.chatbot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IntentEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentEntityAllPropertiesEquals(IntentEntity expected, IntentEntity actual) {
        assertIntentEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertIntentEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentEntityAllUpdatablePropertiesEquals(IntentEntity expected, IntentEntity actual) {
        assertIntentEntityUpdatableFieldsEquals(expected, actual);
        assertIntentEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentEntityAutoGeneratedPropertiesEquals(IntentEntity expected, IntentEntity actual) {
        assertThat(actual)
            .as("Verify IntentEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentEntityUpdatableFieldsEquals(IntentEntity expected, IntentEntity actual) {
        assertThat(actual)
            .as("Verify IntentEntity relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getOptional()).as("check optional").isEqualTo(expected.getOptional()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntentEntityUpdatableRelationshipsEquals(IntentEntity expected, IntentEntity actual) {
        assertThat(actual)
            .as("Verify IntentEntity relationships")
            .satisfies(a -> assertThat(a.getIntents()).as("check intents").isEqualTo(expected.getIntents()));
    }
}
