package io.akhilennu.chatbot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UtteranceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtteranceAllPropertiesEquals(Utterance expected, Utterance actual) {
        assertUtteranceAutoGeneratedPropertiesEquals(expected, actual);
        assertUtteranceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtteranceAllUpdatablePropertiesEquals(Utterance expected, Utterance actual) {
        assertUtteranceUpdatableFieldsEquals(expected, actual);
        assertUtteranceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtteranceAutoGeneratedPropertiesEquals(Utterance expected, Utterance actual) {
        assertThat(actual)
            .as("Verify Utterance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtteranceUpdatableFieldsEquals(Utterance expected, Utterance actual) {
        assertThat(actual)
            .as("Verify Utterance relevant properties")
            .satisfies(a -> assertThat(a.getText()).as("check text").isEqualTo(expected.getText()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtteranceUpdatableRelationshipsEquals(Utterance expected, Utterance actual) {
        assertThat(actual)
            .as("Verify Utterance relationships")
            .satisfies(a -> assertThat(a.getIntent()).as("check intent").isEqualTo(expected.getIntent()));
    }
}
